name: issuer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: 4.3.8
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

