name: issuer
version: 1.0.0+1
publish_to: none
description: A github issue blog generate tool.

environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter

  get: 4.3.8
  github: ^8.1.2
  niku: ^1.1.3
  flutter_dotenv: ^5.0.2

dev_dependencies: 
  build_runner: ^2.1.4
  flutter_lints: ^1.0.0
  get_cli: ^1.6.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

